/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RetrieveRouteImport } from './routes/retrieve'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as TicketRefRouteImport } from './routes/ticket.$ref'
import { Route as AdminSetupRouteImport } from './routes/admin.setup'
import { Route as AdminLogoutRouteImport } from './routes/admin.logout'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminCapacityRouteImport } from './routes/admin.capacity'
import { Route as ApiSelfieKeyRouteImport } from './routes/api.selfie.$key'

const RetrieveRoute = RetrieveRouteImport.update({
  id: '/retrieve',
  path: '/retrieve',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketRefRoute = TicketRefRouteImport.update({
  id: '/ticket/$ref',
  path: '/ticket/$ref',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSetupRoute = AdminSetupRouteImport.update({
  id: '/admin/setup',
  path: '/admin/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLogoutRoute = AdminLogoutRouteImport.update({
  id: '/admin/logout',
  path: '/admin/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCapacityRoute = AdminCapacityRouteImport.update({
  id: '/admin/capacity',
  path: '/admin/capacity',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSelfieKeyRoute = ApiSelfieKeyRouteImport.update({
  id: '/api/selfie/$key',
  path: '/api/selfie/$key',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/register': typeof RegisterRoute
  '/retrieve': typeof RetrieveRoute
  '/admin/capacity': typeof AdminCapacityRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/logout': typeof AdminLogoutRoute
  '/admin/setup': typeof AdminSetupRoute
  '/ticket/$ref': typeof TicketRefRoute
  '/admin/': typeof AdminIndexRoute
  '/api/selfie/$key': typeof ApiSelfieKeyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/register': typeof RegisterRoute
  '/retrieve': typeof RetrieveRoute
  '/admin/capacity': typeof AdminCapacityRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/logout': typeof AdminLogoutRoute
  '/admin/setup': typeof AdminSetupRoute
  '/ticket/$ref': typeof TicketRefRoute
  '/admin': typeof AdminIndexRoute
  '/api/selfie/$key': typeof ApiSelfieKeyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/register': typeof RegisterRoute
  '/retrieve': typeof RetrieveRoute
  '/admin/capacity': typeof AdminCapacityRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/logout': typeof AdminLogoutRoute
  '/admin/setup': typeof AdminSetupRoute
  '/ticket/$ref': typeof TicketRefRoute
  '/admin/': typeof AdminIndexRoute
  '/api/selfie/$key': typeof ApiSelfieKeyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/register'
    | '/retrieve'
    | '/admin/capacity'
    | '/admin/login'
    | '/admin/logout'
    | '/admin/setup'
    | '/ticket/$ref'
    | '/admin/'
    | '/api/selfie/$key'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/register'
    | '/retrieve'
    | '/admin/capacity'
    | '/admin/login'
    | '/admin/logout'
    | '/admin/setup'
    | '/ticket/$ref'
    | '/admin'
    | '/api/selfie/$key'
  id:
    | '__root__'
    | '/'
    | '/register'
    | '/retrieve'
    | '/admin/capacity'
    | '/admin/login'
    | '/admin/logout'
    | '/admin/setup'
    | '/ticket/$ref'
    | '/admin/'
    | '/api/selfie/$key'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RegisterRoute: typeof RegisterRoute
  RetrieveRoute: typeof RetrieveRoute
  AdminCapacityRoute: typeof AdminCapacityRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminLogoutRoute: typeof AdminLogoutRoute
  AdminSetupRoute: typeof AdminSetupRoute
  TicketRefRoute: typeof TicketRefRoute
  AdminIndexRoute: typeof AdminIndexRoute
  ApiSelfieKeyRoute: typeof ApiSelfieKeyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/retrieve': {
      id: '/retrieve'
      path: '/retrieve'
      fullPath: '/retrieve'
      preLoaderRoute: typeof RetrieveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ticket/$ref': {
      id: '/ticket/$ref'
      path: '/ticket/$ref'
      fullPath: '/ticket/$ref'
      preLoaderRoute: typeof TicketRefRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/setup': {
      id: '/admin/setup'
      path: '/admin/setup'
      fullPath: '/admin/setup'
      preLoaderRoute: typeof AdminSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/logout': {
      id: '/admin/logout'
      path: '/admin/logout'
      fullPath: '/admin/logout'
      preLoaderRoute: typeof AdminLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/capacity': {
      id: '/admin/capacity'
      path: '/admin/capacity'
      fullPath: '/admin/capacity'
      preLoaderRoute: typeof AdminCapacityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/selfie/$key': {
      id: '/api/selfie/$key'
      path: '/api/selfie/$key'
      fullPath: '/api/selfie/$key'
      preLoaderRoute: typeof ApiSelfieKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RegisterRoute: RegisterRoute,
  RetrieveRoute: RetrieveRoute,
  AdminCapacityRoute: AdminCapacityRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminLogoutRoute: AdminLogoutRoute,
  AdminSetupRoute: AdminSetupRoute,
  TicketRefRoute: TicketRefRoute,
  AdminIndexRoute: AdminIndexRoute,
  ApiSelfieKeyRoute: ApiSelfieKeyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
